export const GET_COUPONS='GET_COUPONS';
export const GET_COUPON_BY_ID='GET_COUPON_BY_ID';
export const CREATE_COUPON='CREATE_COUPON';
export const UPDATE_COUPON='UPDATE_COUPON';
export const DELETE_COUPON='DELETE_COUPON';

export const CREATE_USER='CREATE_USER';
export const LOGIN_USER='LOGIN_USER';